{"name": "test_login_with_invalid_credentials", "status": "passed", "start": 1697960237998, "stop": 1697960239777, "uuid": "0e10a3a8-bbf2-4cbd-ab9f-bef756d43a77", "historyId": "63d25ff501081fd9ca920ea2a0aa8197", "testCaseId": "63d25ff501081fd9ca920ea2a0aa8197", "fullName": "tests.test_Login.TestLogin#test_login_with_invalid_credentials", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_Login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "soumya"}, {"name": "thread", "value": "25984-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_Login"}]}